### PR TITLE
fix: handle application level errors in celestia-node API

### LINKED ISSUE #416: Improve error handling in Celestia DA
Celestia DA should check for application level errors returned by go-cnc. Especially `/submit_pfd` returns `TxResponse` which contains `Code`. This value should be checked, and appropriate error returned from `SubmitBlock` method.

### PR DESCRIPTION
**Pull request by tzdybal**
Resolves #416.

### CODE REVIEW

**Comment by tzdybal** [comment]
I tested this locally, trying to submit to mamaki. Errors (sequence mismatch) was successfully returned.

File: da/celestia/mock/server.go [hunk 1]
```diff
@@ -89,10 +89,14 @@ func (s *Server) submit(w http.ResponseWriter, r *http.Request) {
 	}
 
 	res := s.mock.SubmitBlock(&block)
+	code := 0
+	if res.Code != da.StatusSuccess {
+		code = 3
```
Comment (liamsi) [inline da/celestia/mock/server.go:94]: why not simply pass the res.Code here?

Comment (tzdybal) [reply da/celestia/mock/server.go:94]: Because it's code from different API, and thus values differ. `da.StatusSuccess` is `1`, and `TxResponse.Code` use `0` to denote success.

Comment (liamsi) [reply da/celestia/mock/server.go:94]: i see. unfortunately, 0 != 1 😄
